import Head from "next/head";
import Image from "next/image";
import { Avatar } from '@mui/material';
import Chip from '@mui/material/Chip';
import Link from '@mui/material/Link';
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import { coinbaseWallet, hooks } from "../components/connectors/coinbaseWallet";
import { useRouter } from "next/router";
import Navbar from "../components/Navbar";
import { Alert } from "@mui/material";
const { useIsActive } = hooks;
import cardStyle from "../styles/Card.module.css";

export default function Home() {
  const router = useRouter();
  const isActive = useIsActive();

  // example loading NFT data
  const [nfts, setNfts] = useState([]);

  useEffect(() => {
    void coinbaseWallet.connectEagerly();
    fetch("/api/getNFTs")
      .then((res) => res.json())
      .then((nfts) => setNfts(nfts));
  }, [nfts]);

  console.log(nfts);
  if (isActive) router.push("/dashboard");
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <div className={styles.section}>
          <h3 className={styles.centered}>
            Welcome to <a>NFTExperience!</a>
          </h3>
          <h1 className={styles.title}>
            Using dynamic NFTs to enhance experiences around the world.
          </h1>
        </div>

        <div className={styles.section}>
          <div style={{
            width: '100%',
            height: 20,
            backgroundColor: 'red',
            display: 'flex',
            justifyContent: 'center',
            marginTop: -60
          }}>
            <Image
              className={styles.image}
              src="/Images/person1.jpeg"
              alt="Picture of the author"
              width={100}
              height={150}
              layout="responsive"
            />
          </div>

          <h2 className={styles.centered}>Featured Experiences</h2>
          <div className={styles.grid}>
            {nfts.map((data, i) => (
              <div key={i} className={styles.card}>
                <h4>{data.expLocation}</h4>
                <h2>{data.expName}</h2>
                <p>{data.expDesc}</p>
                <p className={styles.price}>Price: {data.expPrice}</p>
                <Link href='/experiences'>
                  <a className={styles.buyLink}>Book this experience →</a>
                </Link>
              </div>
            ))}
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
