import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import styles from "../styles/Home.module.css";
import { coinbaseWallet, hooks } from "../components/connectors/coinbaseWallet";
import { useRouter } from "next/router";
import Navbar from "../components/Navbar";
const { useIsActive } = hooks;

export default function Home() {
  const router = useRouter();
  const isActive = useIsActive();
  useEffect(() => {
    void coinbaseWallet.connectEagerly();
  }, []);
  if (isActive) router.push("/dashboard");
  return (
    <div className={styles.container}>
      <Head>
        <title>Mint an Experience</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <div className={styles.section}>
          <h3 className={styles.centered}>
            Mint an <a>NFTExperience!</a>
          </h3>
          <h1 className={styles.title}>
          Mint an Experience!
          </h1>
          <p>
            Fill out the short form below to mint an NFT Experience.
          </p>
        </div>
        <div>
          <form className={styles.form}>
          <label htmlFor="experienceLocation">
              Experience Location:
            </label>
            <input name="experienceLocation" type="text" placeholder="Enter an experience location..."></input>
            <label htmlFor="experienceName">
              Experience Name:
            </label>
            <input name="experienceName" type="text" placeholder="Enter an experience name..."></input>
            <label htmlFor="experienceDescription">
              Experience Description:
            </label>
            <textarea name="experienceDescription" type="text" placeholder="Describe the experience..." />
            <label htmlFor="experiencePrice">
              Experience Price:
            </label>
            <input name="experiencePrice" type="text" placeholder="Enter a price..."></input>
            <button>Mint Experience</button>
          </form>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
